namespace OpenCL.Wrapper.TypeEnums
{
    /// <summary>
    /// An Enum containing all possible data types that plain OpenCL can handle
    /// </summary>
    public enum DataVectorTypes
    {

        Unknown,
        Float1,
        Float2,
        Float3,
        Float4,
        Float8,
        Float16,
        Int1,
        Int2,
        Int3,
        Int4,
        Int8,
        Int16,
        Uint1,
        Uint2,
        Uint3,
        Uint4,
        Uint8,
        Uint16,
        Char1,
        Char2,
        Char3,
        Char4,
        Char8,
        Char16,
        Uchar1,
        Uchar2,
        Uchar3,
        Uchar4,
        Uchar8,
        Uchar16,
        Short1,
        Short2,
        Short3,
        Short4,
        Short8,
        Short16,
        Ushort1,
        Ushort2,
        Ushort3,
        Ushort4,
        Ushort8,
        Ushort16,
        Long1,
        Long2,
        Long3,
        Long4,
        Long8,
        Long16,
        Ulong1,
        Ulong2,
        Ulong3,
        Ulong4,
        Ulong8,
        Ulong16

    }
}